### ISSUE TITLE
Swift 3 Support

### ISSUE THREAD

**Issue by USSliberty** [kean/Arranged#3]
Hi, i have just install your project from cocoapods. 
However it seems that the code is written in Swift 2.0 and my main project is using Swift 3.0, so i have a lot of issues when I build the project. 

I see also here in github you have updated the repo to Swift 3.0, what I am missing here?

**Comment by kean** [comment]
Hey! Apparently, I haven't finished the transition yet (I don't remember actually). I'll get back to it as soon as I can.

Btw, most projects have updated to support iOS 9+ only which includes UIStackView. I'd suggest to stick with UIStackView.

**Comment by larslockefeer** [comment]
`master` is working just fine, so I think all that is needed is a new release. I can submit a PR for that if you want.

**Comment by kean** [comment]
Just pushed a new version (2.0) myself. Enjoy 🍻

**Comment by larslockefeer** [comment]
Thanks! 🎉

**Comment by USSliberty** [comment]
Thank you guys! 

-- Inviato da iPhone
